export default {
	TOGGLE_VISUALIZER: "TOGGLE_VISUALIZER",
	UPDATE_PLAYLISTS: "UPDATE_PLAYLISTS",
	SELECT_PLAYLIST: "SELECT_PLAYLIST",
	SET_TOKEN: "SET_TOKEN",
	SET_USER_ID: "SET_USER_ID",
	UPDATE_TRACKS: "UPDATE_TRACKS",
}
